export const FETCH_DATA = "FETCH_DATA";

export const REQUEST_PENDING = 'REQUEST_ROBOTS_PENDING';
export const REQUEST_SUCCESS = 'REQUEST_ROBOTS_SUCCESS';
export const REQUEST_FAILED = 'REQUEST_ROBOTS_FAILED';

export const IS_EMAIL ='IS_EMAIL';
export const IS_PASSWORD = 'IS_PASSWORD';
export const IS_EMAIL_VALID = 'IS_EMAIL_VALID';
export const IS_PASSWORD_VALID = 'IS_PASSWORD_VALID';
export const IS_SHOW_PASSWORD = 'IS_SHOW_PASSWORD';
export const IS_NAME = "IS_NAME";