export const FETCH_DATA = "FETCH_DATA";

export const REQUEST_PENDING = 'REQUEST_ROBOTS_PENDING';
export const REQUEST_SUCCESS = 'REQUEST_ROBOTS_SUCCESS';
export const REQUEST_FAILED = 'REQUEST_ROBOTS_FAILED';